---
- name: Schedule job template
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create schedule for job template
      ansible.controller.schedule:
        name: "Monthly Job"
        rrule: "DTSTART;TZID=Australia/Melbourne:20230101T020000 RRULE:FREQ=MONTHLY;BYDAY=2TH"
        unified_job_template: "111"
        state: present
